### ISSUE TITLE
device not supported message

### ISSUE THREAD

**Issue by prtrjan** [mabu4ch/iConfig#20]
![835FB663-C88B-4DEE-A5F7-949D29DD11E4](https://user-images.githubusercontent.com/115892957/196007460-ef16ea38-b206-453b-a0c0-a16a1dec6644.jpeg)

I’m getting the above message for my audio4c

**Comment by prtrjan** [comment]
Great, thanks!

**Comment by mabu4ch** [comment]
The new Version has just been approved for the app store. Good luck

**Comment by prtrjan** [comment]
Thank you so much!

Op do 27 okt. 2022 om 14:38 schreef Markus Burri ***@***.***>:
